#!/bin/sh

PREFIX="`pwd`/local"
TARGET=i586-elf
CC=/usr/bin/gcc-4.7
CXX=/usr/bin/g++-4.7
CPP=/usr/bin/cpp-4.7
LD=/usr/bin/gcc-4.7
PATH=$PATH:$PREFIX/bin


pushd local/build-gcc

../../src/gcc-4.7.2/configure --target=$TARGET --prefix=$PREFIX --disable-nls \
                              --enable-languages=c,c++ --without-headers

make all-gcc
make install-gcc

make all-target-libgcc
make install-target-libgcc
