#!/bin/sh

PREFIX="`pwd`/local"
TARGET=i586-elf
CC=/usr/bin/gcc-4.7
CXX=/usr/bin/g++-4.7
CPP=/usr/bin/cpp-4.7
LD=/usr/bin/gcc-4.7

mkdir local

pushd local

mkdir build-binutils build-gcc

pushd ./build-binutils

../../src/binutils-2.23/configure --target=$TARGET --prefix=$PREFIX --disable-nls
make all
make install
