#!/bin/bash

mkdir src

pushd src

wget http://ftp.gnu.org/gnu/binutils/binutils-2.23.tar.gz

tar -xzvpf binutils-2.23.tar.gz

wget http://ftp.gnu.org/gnu/gcc/gcc-4.7.2/gcc-4.7.2.tar.gz

tar -xzvpf gcc-4.7.2.tar.gz
